# Generated by Django 2.0.4 on 2018-05-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
